### ISSUE TITLE
Login in options

### ISSUE THREAD

**Issue by AnaisGueyte** [AnaisGueyte/CI-entrenous#8]
Login in options

- [x] Design of pages

- [x] Get proper error message / design 

- [ ] Option to save pseudo/password in lowercase in extra

- [x] Crypte password plz...

- [x] renew password options

- [x] Error when trying to login in while no account existing

- [x] Security on creating new user

- [x] PHP error on "save search" mapview when new user register

**Comment by AnaisGueyte** [comment]
it looks so pretty now ! Design re-done !

**Comment by AnaisGueyte** [comment]
renew password options - Before having the mail server, it will be the mail to webmaster option

**Comment by flo30240** [comment]
Error on registration
